name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

concurrency:
    group: CI
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node, Yarn, and NPM
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Setup Docker
              uses: docker/setup-buildx-action@v1
              id: buildx
              with:
                  install: true
            - name: Install Dependencies
              run: yarn
            - name: Lint App
              run: yarn run lint
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node, Yarn, and NPM
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Setup Docker
              uses: docker/setup-buildx-action@v1
              id: buildx
              with:
                  install: true
            - name: Install Dependencies
              run: yarn
            - name: Build App
              run: yarn run build:output
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node, Yarn, and NPM
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Setup Docker
              uses: docker/setup-buildx-action@v1
              id: buildx
              with:
                  install: true
            - name: Install Dependencies
              run: yarn
            - name: Test App
              run: yarn run test:output
            - name: Upload Test Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage
            - name: Generate Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.0.2
              with:
                  filename: coverage/cobertura-coverage.xml
                  badge: true
                  format: 'markdown'
                  output: 'both'
            - name: Add Code Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                  recreate: true
                  path: code-coverage-results.md
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node, Yarn, and NPM
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Install Dependencies
              run: yarn
            - name: Download Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: dist
            - name: Create Semantic GitHub Release
              run: yarn run release
