name: CD

on:
    workflow_run:
        workflows: ['CI']
        branches: [master]
        types:
            - completed

env:
    DEPLOY_URL_PROD: https://me.nodnarb.dev

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        concurrency:
            group: CD-production
            cancel-in-progress: true
        environment:
            name: production
            url: ${{ env.DEPLOY_URL_PROD }}
        steps:
            - name: Echo all secrets
              env:
                  ALL_SECRETS: ${{ toJson(secrets) }}
              run: echo "$ALL_SECRETS"
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ci.yml
                  name: dist
