name: CD

on:
    release:
        types:
            - published

env:
    DEPLOY_URL_PROD: https://me.nodnarb.dev

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        concurrency:
            group: CD-production
            cancel-in-progress: true
        environment:
            name: production
            url: ${{ env.DEPLOY_URL_PROD }}
        steps:
            - name: Download Release Asset
              uses: dsaltares/fetch-gh-release-asset@v0.06
              with:
                  file: 'dist.tar.gz'
                  target: 'dist.tar.gz'
                  token: ${{ github.token }}
            - name: Echo secrets
              env:
                  SECRETS: ${{ toJson(secrets) }}
              run: echo "$SECRETS"
